# Generated by Django 3.1.1 on 2020-09-08 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendreq', '0002_auto_20200908_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsfound',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendreq.itemrequest'),
        ),
    ]
