# Generated by Django 3.1 on 2020-08-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('address_street', models.CharField(max_length=100)),
                ('address_home_number', models.IntegerField()),
                ('address_city', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('field_of_study', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('current_year', models.CharField(max_length=50)),
                ('scholarship', models.CharField(max_length=100)),
                ('type_of_friendship', models.CharField(max_length=100)),
            ],
        ),
    ]
