# Generated by Django 3.1.1 on 2020-09-09 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('student_id', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('home_address', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('BA', 'BA'), ('BSC', 'BSC'), ('MA', 'MA'), ('MSC', 'MSC'), ('PHD', 'PHD')], default='BA', max_length=100)),
                ('scholarship', models.CharField(max_length=100)),
                ('membership_type', models.CharField(choices=[('friend', 'friend'), ('coordinator', 'coordinator')], default='friend', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
