# Generated by Django 3.1.1 on 2020-09-28 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_house_number',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Please enter a valid number from 1 to 999.', regex='\\d{1,3}')], verbose_name='home_number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 05XXXXXXXX.', regex='^05[0-68-9][0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='ID must be 9 digits long.', regex='\\d{8,9}')]),
        ),
    ]
