# Generated by Django 3.1 on 2020-09-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200831_0752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
