# Generated by Django 3.1.1 on 2020-09-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friendreq', '0003_auto_20200908_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatedItems',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('20009', 'closet'), ('20016', 'bed'), ('20008', 'chair'), (
                    '10006', 'fridge'), ('10029', 'Washing machine'), ('20017', 'sofa')], max_length=40)),
                ('transfer_date', models.DateField()),
                ('student_phone_number', models.CharField(max_length=10)),
                ('pickup_time', models.TimeField()),
                ('pickup_location', models.CharField(choices=[('Tel Aviv', 'Tel Aviv'), ('Jerusalem', 'Jerusalem'), (
                    'Beer Sheva', 'Beer Sheva'), ('Haifa', 'Haifa'), ('Modiin', 'Modiin'), ('Hasharon', 'Hasharon')], max_length=40)),
                ('drop_off_time', models.TimeField()),
                ('drop_off_location', models.CharField(choices=[('Tel Aviv', 'Tel Aviv'), ('Jerusalem', 'Jerusalem'), (
                    'Beer Sheva', 'Beer Sheva'), ('Haifa', 'Haifa'), ('Modiin', 'Modiin'), ('Hasharon', 'Hasharon')], max_length=40)),
                ('request_id', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='friendreq.itemrequest')),
            ],
        ),
    ]
